version: '2'
services:

  nginx:
    build: ./lb
    links:
      - server1
      - server2
    ports:
      - "8000:8000"

  server1:
    build: ./server
    links:
      - redis
    environment:
      - REDIS_SVR=redis
    ports:
      - "7000"

  server2:
    build: ./server
    links:
      - redis
    environment:
      - REDIS_SVR=redis
    ports:
      - "7000"

  server3:
    build: ./server
    links:
      - redis
    environment:
      - REDIS_SVR=redis
    ports:
      - "7000"

  redis:
    image: daocloud.io/redis:latest
    ports:
      - "6379"

