version: '2'
services:
  putter:
    build: ./putter1
    environment:
      - REDIS_SRV=redis

  getter:
    build: ./getter
    environment:
      - REDIS_SRV=redis

  redis:
    image: daocloud.io/redis:latest
    ports:
      - "6379"
