version: '2'
services:

  server1:
    build: ./server
    links:
      - redis
    environment:
      - REDIS_SVR=redis
    ports:
      - "7000:7000"

  server2:
    build: ./server
    links:
      - redis
    environment:
      - REDIS_SVR=redis
    ports:
      - "7001"

  redis:
    image: daocloud.io/redis:latest
    ports:
      - "6379"

